# Generated by Django 3.2.12 on 2022-05-26 19:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('home', '0005_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='portafolio',
            new_name='Portfolio',
        ),
    ]
