# Generated by Django 3.2.20 on 2023-08-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='github_url',
            field=models.URLField(blank=True, help_text='Share your Github Profile', null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Share your LinkedIn Profile', null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Share your Twitter Profile', null=True),
        ),
    ]
