# Generated by Django 3.2.20 on 2023-08-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20230816_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='is_collaborator',
            field=models.BooleanField(default=False, help_text='Check here if you would like to collaborate via GitHub'),
        ),
    ]
