# Generated by Django 3.2.20 on 2023-11-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_signature_is_collaborator'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('application_type', models.CharField(choices=[('mentor', 'Mentor'), ('intern', 'Intern/Junior Developer')], max_length=6)),
                ('experience', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter_name', models.CharField(max_length=100)),
                ('submitter_email', models.EmailField(max_length=254)),
                ('project_title', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
            ],
        ),
    ]
